name: My example workflow

on:  push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "my example Github Actions Job"

        - name: List files
          run: ls
 
        - name: Read file
          run: cat README.md	