name: my-new-Node.js CI/CD
on: 
  workflow_dispatch: # Manual trigger

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.hash.outputs.hash }}
      lockfile-exists: ${{ steps.check-lockfile.outputs.exists }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for lockfile
      id: check-lockfile
      run: |
        if [ -f package-lock.json ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "file=package-lock.json" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "file=package.json" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate dependency hash
      id: hash
      run: |
        if [ -f package-lock.json ]; then
          echo "hash=$(shasum package-lock.json | cut -d ' ' -f1)" >> $GITHUB_OUTPUT
        else
          echo "hash=$(shasum package.json | cut -d ' ' -f1)" >> $GITHUB_OUTPUT
        fi

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        # Use the actual file path, not the hash
        cache-dependency-path: |
          package-lock.json
          package.json
    
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    
    - name: Build project
      run: npm run build
      
    - uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/