name: New-Workflow-Node.js CI/CD

on: 
  workflow_dispatch:  # Manually triggered

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.hash.outputs.hash }}
    steps:
    - uses: actions/checkout@v4
    - name: Generate dependency hash
      id: hash
      run: echo "hash=$(shasum package-lock.json | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build  # Requires "build" script in package.json

    - uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/  # Ensure this matches your build output directory

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm ci

    - uses: actions/download-artifact@v4
      with:
        name: build-output
        path: dist/  # Overwrites local dist/ with the built artifact

    - run: npm test  # Requires "test" script in package.json

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'  # Runs only on main branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-output
        path: dist/

    - name: Deploy to production
      run: chmod +x ./deploy-script.sh && ./deploy-script.sh